#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

source "${SCRIPT_DIR}/../common/multi_task_common.sh"

MODEL_FAMILY="${MODEL_FAMILY:?set MODEL_FAMILY before sourcing opd_train.sh}"
MODEL_SIZE="${MODEL_SIZE:?set MODEL_SIZE before sourcing opd_train.sh}"

PROJECT_NAME="${PROJECT_NAME:-VideoProxy-opd}"
EXP_NAME="${EXP_NAME:-${MODEL_FAMILY}_${MODEL_SIZE}_opd}"
TASKS="${TASKS:-tg mcq aot}"
TRAINING_MODE="opd"
ADV_ESTIMATOR="${ADV_ESTIMATOR:-grpo}"
ONLINE_FILTERING=false
DISABLE_KL=false
USE_KL_LOSS=false
ROLLOUT_N=1
ROLLOUT_TEMPERATURE="${ROLLOUT_TEMPERATURE:-1.0}"
ENTROPY_COEFF="${ENTROPY_COEFF:-0.0}"
OPD_TOPK="${OPD_TOPK:-10}"
OPD_KL_COEF="${OPD_KL_COEF:-1.0}"

if [[ -z "${TEACHER_MODEL_PATH:-}" && -z "${AOT_TEACHER_MODEL_PATH:-}" ]]; then
    echo "[opd-train] ERROR: set TEACHER_MODEL_PATH=/path/to/teacher or all multi-teacher paths." >&2
    exit 1
fi

N_GPUS_PER_NODE="${N_GPUS_PER_NODE:-2}"
NNODES="${NNODES:-1}"
TP_SIZE="${TP_SIZE:-1}"
ROLLOUT_BS="${ROLLOUT_BS:-16}"
GLOBAL_BS="${GLOBAL_BS:-16}"
MB_PER_UPDATE="${MB_PER_UPDATE:-1}"
MB_PER_EXP="${MB_PER_EXP:-1}"
MAX_FRAMES="${MAX_FRAMES:-256}"
MAX_PIXELS="${MAX_PIXELS:-65536}"
MAX_PROMPT_LEN="${MAX_PROMPT_LEN:-14000}"
MAX_RESPONSE_LEN="${MAX_RESPONSE_LEN:-256}"
ROLLOUT_GPU_MEM_UTIL="${ROLLOUT_GPU_MEM_UTIL:-0.35}"
ROLLOUT_MAX_BATCHED_TOKENS="${ROLLOUT_MAX_BATCHED_TOKENS:-20480}"
DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS:-4}"
DATALOADER_PREFETCH_FACTOR="${DATALOADER_PREFETCH_FACTOR:-2}"
DATALOADER_PERSISTENT_WORKERS="${DATALOADER_PERSISTENT_WORKERS:-false}"
DATALOADER_PIN_MEMORY="${DATALOADER_PIN_MEMORY:-false}"
VAL_BEFORE_TRAIN="${VAL_BEFORE_TRAIN:-false}"
VAL_FREQ="${VAL_FREQ:-50}"
SAVE_FREQ="${SAVE_FREQ:-50}"
SAVE_LIMIT="${SAVE_LIMIT:-3}"
MAX_STEPS="${MAX_STEPS:-50}"

MIN_ROLLOUT_MAX_BATCHED_TOKENS=$((MAX_PROMPT_LEN + MAX_RESPONSE_LEN))
if (( ROLLOUT_MAX_BATCHED_TOKENS < MIN_ROLLOUT_MAX_BATCHED_TOKENS )); then
    echo "[opd-train] ERROR: ROLLOUT_MAX_BATCHED_TOKENS=${ROLLOUT_MAX_BATCHED_TOKENS} must be >= MAX_PROMPT_LEN + MAX_RESPONSE_LEN = ${MIN_ROLLOUT_MAX_BATCHED_TOKENS}" >&2
    exit 1
fi

echo "[opd-train] MODEL_FAMILY=${MODEL_FAMILY} MODEL_SIZE=${MODEL_SIZE}"
echo "[opd-train] MODEL_PATH=${MODEL_PATH}"
echo "[opd-train] EXP_NAME=${EXP_NAME} TASKS=${TASKS}"
echo "[opd-train] OPD_TOPK=${OPD_TOPK} OPD_KL_COEF=${OPD_KL_COEF}"

source "${SCRIPT_DIR}/../launchers/run_multi_task.sh"
